<?xml version="1.0"?>

<robot>

<gazebo reference="body_link">
<kp>1000000.0</kp>
<kd>100.0</kd>
<mu1>1.0</mu1>
<mu2>1.0</mu2>
<material>Gazebo/Red</material>
</gazebo>

<gazebo reference="wheel1_link">
<kp>1000000.0</kp>
<kd>100.0</kd>
<mu1>1.0</mu1>
<mu2>1.0</mu2>
<material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference="wheel2_link">
<kp>1000000.0</kp>
<kd>100.0</kd>
<mu1>1.0</mu1>
<mu2>1.0</mu2>
<material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference="wheel3_link">
<kp>1000000.0</kp>
<kd>100.0</kd>
<mu1>1.0</mu1>
<mu2>1.0</mu2>
<material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference="wheel4_link">
<kp>1000000.0</kp>
<kd>100.0</kd>
<mu1>1.0</mu1>
<mu2>1.0</mu2>
<material>Gazebo/Yellow</material>
</gazebo>

<ros2_control name="GazeboSystem" type="system">
    <hardware>
        <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <!-- <joint name="wheel1_joint">
        <command_interface name="position">
            <param name="min">-6.2832</param>
            <param name="max">6.2832</param>
        </command_interface>
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort" />
    </joint> -->

</ros2_control>

<gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
        <!-- <robot_sim_type>gazebo_ros2_control/DefaultRobotHWSim</robot_sim_type> -->
        <robot_sim_type>gazebo_ros2_control/GazeboSystem</robot_sim_type>
        <parameters>/home/a/robotics-lab/final-project/robotics-assignment/ros_ws/src/simple_robot_description/config/robot.yaml</parameters>
    </plugin>
</gazebo>

<gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <update_rate>500</update_rate>
            
        <!-- <num_wheel_pairs>2</num_wheel_pairs> -->
                
        <left_joint>wheel2_joint</left_joint>
        <right_joint>wheel1_joint</right_joint>        

        <!-- <left_joint>wheel4_joint</left_joint>
        <right_joint>wheel3_joint</right_joint>         -->

        <wheel_separation>${body_link_y_dim+wheel_link_length}</wheel_separation>
        <wheel_separation>${body_link_y_dim+wheel_link_length}</wheel_separation>

        <wheel_diameter>${2*wheel_link_radius}</wheel_diameter>
        <wheel_diameter>${2*wheel_link_radius}</wheel_diameter>

        <max_wheel_torque>200</max_wheel_torque>
        <max_wheel_acceleration>10.0</max_wheel_acceleration>

        <command_topic>cmd_vel</command_topic>
        <odometry_topic>odom</odometry_topic>
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>dummy</robot_base_frame>
        <publish_wheel_tf>true</publish_wheel_tf>
        <publish_odom>true</publish_odom>


        <covariance_x>0.0001</covariance_x>
        <covariance_y>0.0001</covariance_y>
        <covariance_yaw>0.01</covariance_yaw>
    </plugin>
</gazebo>
 
</robot>